config/routes.rb
Rails.application.routes.draw do
  resources :niches do
    collection do
      post :move
      get :highlight
    end
  end
  resources :items

  post 'free_item', action: :show_free_item, controller: 'welcome'

  post 'new_request', action: :new, controller: 'free_item_requests'
  post 'give_away', action: :give_away, controller: 'free_item_requests'
  get 'filter_notifications', action: :filter_notifications, controller: 'free_item_requests'

  get 'generate_link', action: :generate_link, controller: 'shared_items'
  get 'share', action: :share, controller: 'shared_items'
  resources :rent_items, only: %i[show edit update] do
    collection do
      get 'rent_form'
      post 'rent'
      delete 'repay'
    end
  end
  resources :categories do
    collection do
      post :move
    end
  end
  match "/404", to: 'errors#not_found', via: :all
  match "/500", to: 'errors#internal_server_error', via: :all
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }
  resources :users
  match '/users/:id/finish_signup' => 'users#finish_signup', via: %i[get patch], :as => :finish_signup
  match '/users/:id/settings' => 'users#settings', via: %i[get patch], :as => :settings
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.slim
.legal
  .copyright
    | © 2018 Rubizza - Nicher+r.

app/views/shared/_menu.html.slim
.menu
  ul.list
    li
      = link_to(root_path)
        i.material-icons home
        span Home
    li
      = link_to(items_path)
        i.material-icons widgets
        span Items
    li
      a href=niches_path
        i.material-icons dns
        span Niches
    li
      a href=categories_path
        i.material-icons loyalty
        span Categories
    li.header
    li
      a href= settings_path(current_user.id)
        i.material-icons settings
        span Settings

app/views/shared/_navbar.html.slim
nav.navbar.navbar-fixed-top
  .container-fluid
    .navbar-header
      a.navbar-toggle.collapsed aria-expanded="false" data-target="#navbar-collapse" data-toggle="collapse" href="javascript:void(0);"
      - if user_session
        a.bars href="javascript:void(0);"
      a.navbar-brand  NICHER+R
    #navbar-collapse.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          a.js-search data-close="true" href="javascript:void(0);"
            i.material-icons search
        - if user_session && !current_user.pending_requests.empty?
          li
            = link_to filter_notifications_path do
              i.material-icons notifications_active
        - unless user_session
          li
            = link_to new_user_session_path
              i.material-icons exit_to_app

app/views/shared/_user_info.html.slim
.user-info
  figure
    img.img-circle.img-responsive[src=current_user&.user_profile&.avatar&.small&.url width="50" height="50"]
  .info-container
    .name aria-expanded="false" aria-haspopup="true" data-toggle="dropdown"  #{current_user&.user_profile&.full_name}
    .email #{current_user.email}
    .btn-group.user-helper-dropdown
      i.material-icons aria-expanded="true" aria-haspopup="true" data-toggle="dropdown"  keyboard_arrow_down
      ul.dropdown-menu.pull-right
        li
          a href= user_path(current_user.id)
            i.material-icons> person
            | Profile
        li.divider role="separator"
        li
          a data-method="delete" href= destroy_user_session_path
            i.material-icons> input
            | Sign Out