config/routes.rb
Rails.application.routes.draw do
  resources :niches do
    collection do
      post :move
      get :highlight
    end
  end
  resources :items

  post 'free_item', action: :show_free_item, controller: 'welcome'

  post 'new_request', action: :new, controller: 'free_item_requests'
  post 'give_away', action: :give_away, controller: 'free_item_requests'
  get 'filter_notifications', action: :filter_notifications, controller: 'free_item_requests'

  get 'generate_link', action: :generate_link, controller: 'shared_items'
  get 'share', action: :share, controller: 'shared_items'
  resources :rent_items, only: %i[show edit update] do
    collection do
      get 'rent_form'
      post 'rent'
      delete 'repay'
    end
  end
  resources :categories do
    collection do
      post :move
    end
  end
  match "/404", to: 'errors#not_found', via: :all
  match "/500", to: 'errors#internal_server_error', via: :all
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }
  resources :users
  match '/users/:id/finish_signup' => 'users#finish_signup', via: %i[get patch], :as => :finish_signup
  match '/users/:id/settings' => 'users#settings', via: %i[get patch], :as => :settings
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_items, only: :index
  before_action :free_items_for_unauthorized_user, only: :index, if: -> { !current_user }

  def index; end

  def set_items
    @items = Item.includes(:rent_item, :free_item_request, :niche).for_user(current_user)
                 .or(Item.includes(:rent_item, :free_item_request, :niche).free.non_user(current_user))
    return if params[:search].blank?
    @items = @items.search(params[:search])
  end

  def show_free_item
    @item = Item.free.find(params[:id])
    render 'show_free_item'
  end

  private

  def free_items_for_unauthorized_user
    Item.free.search(params[:search]).sample(8)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_card.html.slim
.col-lg-3.col-md-3.col-sm-6.col-xs-12
  .card
    - if user_session
      .header.bg
        - if current_user.id != item.user_id
          = link_to free_item_path(id: item.id), method: :post do
            h2 = item.title
        - else
          = link_to item
            h2 = item.title
        ul.header-dropdown.m-r-0
          - unless item.rent_item
            - if !current_user.items.exists?(id: item.id) && item.free_item_request.nil?
              li
                .tooltip
                  = link_to new_request_path(item_id: item.id), method: :post, data: { confirm: "Are you sure you want to take this item?" } do
                    i.material-icons pan_tool
                  .tooltiptext Click to request taking this item
            - if item.free_item_request && current_user.items.exists?(id: item.id)
              li
                .tooltip
                  = link_to give_away_path(id: item.free_item_request.id, item_id: item.id), method: :post, data: { confirm: 'Are you sure you want to give away this item?' } do
                    i.material-icons notifications_active
                  .tooltiptext
                    = item.free_item_request.potential_owner.user_profile.first_name
                    = ' wants to take this item, click to give away'
    - else
      .header.bg
        = link_to item do
          h2 = item.title
        ul.header-dropdown.m-r-0
          li
            = link_to new_request_path(item_id: item.id), method: :post, data: { confirm: "Are you sure you want to take this item?" } do
              i.material-icons pan_tool
    .body
      - unless item.attachments.empty?
        .avatar-center
          .rounded
            img.img-responsive[src=item.attachments.first.list_size.url]
      - if current_user&.items&.exists?(id: item.id) && item.niche
        = 'niche: '
        = item.niche&.name

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>
<p>Find me in app/views/welcome/home.html.erb</p>

app/views/welcome/index.html.slim
- if user_session
  .row.clearfix
    = render partial: 'card', collection: @items, as: :item
- else
  .main_welcome
    #welcome.page
      h1#text
        | “One can never have enough socks.”
      = image_tag 'photo_2018-08-28_10-57-50.jpg', height: '100', width: '300', id: 'image'
    .page
      #free-items.row.clearfix
        = render partial: 'card', collection: @items, as: :item

app/views/welcome/show_free_item.html.slim
.row.clearfix
  .col-xs-12.col-sm-12.col-md-12.col-lg-12
    .card
      .header
        h2
          = @item.title
      .body
        .row.clearfix
          .col-xs-12.col-sm-6.col-md-6.col-lg-6
            - if @item.attachments.any?
              = render partial: 'items/slider', locals: {item: @item}
            - else
              = image_tag('page_size_image.png', style: 'width:450px;height:300px;')
          .col-xs-12.col-sm-6.col-md-6.col-lg-6
            .text-left
              h2 Description
            .buttons
              = link_to 'Back', root_path, class: 'btn bg-blue-grey btn-lg'