config/routes.rb
Rails.application.routes.draw do
  resources :niches do
    collection do
      post :move
      get :highlight
    end
  end
  resources :items

  post 'free_item', action: :show_free_item, controller: 'welcome'

  post 'new_request', action: :new, controller: 'free_item_requests'
  post 'give_away', action: :give_away, controller: 'free_item_requests'
  get 'filter_notifications', action: :filter_notifications, controller: 'free_item_requests'

  get 'generate_link', action: :generate_link, controller: 'shared_items'
  get 'share', action: :share, controller: 'shared_items'
  resources :rent_items, only: %i[show edit update] do
    collection do
      get 'rent_form'
      post 'rent'
      delete 'repay'
    end
  end
  resources :categories do
    collection do
      post :move
    end
  end
  match "/404", to: 'errors#not_found', via: :all
  match "/500", to: 'errors#internal_server_error', via: :all
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }
  resources :users
  match '/users/:id/finish_signup' => 'users#finish_signup', via: %i[get patch], :as => :finish_signup
  match '/users/:id/settings' => 'users#settings', via: %i[get patch], :as => :settings
  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  PARAMS = [:title, :description, :free, :niche_id, :category_id, { attachments: [] }].freeze
  LIMIT_OF_ATTACHMENTS = 5
  scope :free, -> { where(free: true) }

  scope :for_user, ->(user) { where(user: user) }
  scope :non_user, ->(user) { where.not(user: user) }
  scope :search, ->(word) { where('title ilike ?', "%#{word}%") }
  acts_as_paranoid
  audited on: :update

  has_one :shared_item, dependent: :destroy

  belongs_to :user
  belongs_to :niche, optional: true

  belongs_to :category, optional: true

  belongs_to :rent_item, optional: true

  validates :title, presence: true

  has_many :item_histories, dependent: :destroy

  belongs_to :free_item_request, optional: true

  mount_uploaders :attachments, ImageUploader
  validates :attachments, file_size: { less_than: 10.megabytes }
  validate :images_count_validation

  def images_count_validation
    errors.add(:attachments, 'must not contain more than 5 files') if attachments.size > LIMIT_OF_ATTACHMENTS
  end

  def display_created_at
    created_at.strftime '%B %e, %Y'
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ApplicationConcern

  before_action :set_item, only: %i[show edit update destroy]
  before_action :set_all_items, only: %i[index]
  helper_method :sort_column, :sort_direction

  def index; end

  def show; end

  def new
    @item = current_user.items.build
  end

  def edit; end

  def create
    @item = current_user.items.new(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private

  def sortable_columns
    %w[title created_at]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : 'title'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def set_item
    @item = Item.find_by!(id: params[:id], user: current_user, rent_item_id: nil, user_id: current_user.id)
  end

  def item_params
    model_params(:item)
  end

  def set_all_items
    set_user_items
    @lend_items = current_user.lend_items.includes(:item)
    @borrowed_items = current_user.borrowed_items.includes(:item)
  end

  def set_user_items
    @items = current_user.items.includes(:category, :niche).order("#{sort_column} #{sort_direction}")
                         .paginate(page: params[:page], per_page: 3).where(rent_item_id: nil)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title.to_s.html_safe, column: column, direction: direction
  end

  def search_for_first_niche(audit)
    Niche.find(audit.audited_changes['niche_id'].first)
  end

  def search_for_last_niche(audit)
    Niche.find(audit.audited_changes['niche_id'].last)
  end

  def search_for_first_category(audit)
    Category.find(audit.audited_changes['category_id'].first)
  end

  def search_for_last_category(audit)
    Category.find(audit.audited_changes['category_id'].last)
  end
end

app/views/items/_category_changed.html.slim
li
  i.fa.fa-tag.bg-lime
  .timeline-item
    span.time
      i.fa.fa-clock-o = audit.created_at.strftime ('%k:%M')
    - if audit.audited_changes['category_id'].last.nil?
      h3.timeline-header Category deleted
    - else
      h3.timeline-header Category changed
      .timeline-body
        p
          - unless audit.audited_changes['category_id'].first.nil?
            b = search_for_first_category(audit).name
          = ' to '
          b = search_for_last_category(audit).name
          = '.'

app/views/items/_description_changed.html.slim
li
  i.fa.fa-list-alt.bg-teal
  .timeline-item
    span.time
      i.fa.fa-clock-o = audit.created_at.strftime '%k:%M'
    - if audit.audited_changes['description'].last.blank?
      h3.timeline-header Description deleted
    - else
      h3.timeline-header Description changed
      .timeline-body
        p
          b = audit.audited_changes['description'].first
          = ' to '
          b = audit.audited_changes['description'].last
          = '.'

app/views/items/_form.html.slim
= form_with(model: item, local: true) do |form|
  - if item.errors.any?
    #error_explanation.alert.alert-warning
      ul
        - item.errors.full_messages.each do |message|
          li= message
  = form.label :title
  .form-group
    .form-line
      = form.text_field :title, class: 'form-control'
  = form.label :description
  .form-group
    .form-line
      = form.text_area :description, class: 'form-control'
  = form.label :niche_id
  .form-group
    .form-line
      = form.collection_select(:niche_id, current_user.niches, :id, :name, { include_blank: true }, { class: "bootstrap-select form-control show-tick" })
  = form.label :category_id
  .form-group
    .form-line
      = form.collection_select(:category_id, current_user.categories, :id, :name, { include_blank: "Please select" }, { class: "bootstrap-select form-control show-tick" })
  = form.check_box :free
  = form.label :free
  br
  = form.label :attachments
  br
  label.btn.btn-primary.waves-effect
    i.material-icons publish
    span ADD PHOTOS
    span.span-file-input
      = form.file_field :attachments, multiple: true
  br
  br
  .button-demo
    = form.button 'Save', type: :submit, class: 'btn btn-primary waves-effect'
    = link_to 'Cancel', items_path, class: 'btn btn-danger waves-effect'

app/views/items/_item_table.html.slim
tr
  td= link_to item.title, item
  td
    - if item.free
      .tooltip
        i.material-icons card_giftcard
        .tooltiptext This item is free
  td.hidden-xs.hidden-sm= item.niche&.name
  td.hidden-xs.hidden-sm= item.category&.name
  td.hidden-xs.hidden-sm= item.display_created_at
  td
    .tooltip
      = link_to nil, class: 'lend_item', data: { id: item.id } do
        i.material-icons swap_horiz
      .tooltiptext Click to lend this item to contact
  td
    .tooltip
      = link_to nil, class: 'share_item', data: { id: item.id } do
        i.material-icons share
      .tooltiptext Click to generate link to lend item
  td.hidden-xs.hidden-sm
    .tooltip
      = link_to edit_item_path(item) do
        i.material-icons edit
      .tooltiptext Edit item
  td
    .tooltip
      = link_to '#', data: { toggle: "modal", id: item.id, target: "#modal" }, class: 'deleteitem' do
        i.material-icons.col-red delete
      .tooltiptext Delete item
  - if item.niche&.url.present?
    td= link_to nil, class: 'highlight', data: { id: item.niche_id } do
      i.material-icons.col-orange lightbulb_outline
  - else
    td

app/views/items/_niche_changed.html.slim
li
  i.fa.fa-cubes.bg-pink
  .timeline-item
    span.time
      i.fa.fa-clock-o = audit.created_at.strftime '%k:%M'
    h3.timeline-header Niche changed
    .timeline-body
      p
        - if audit.audited_changes['niche_id'].first.nil?
          = 'Nowhere'
        - else
          b = search_for_first_niche(audit).name
        = ' to '
        b = search_for_last_niche(audit).name
        = '.'

app/views/items/_rent_item_changed.html.slim
li
  i.fa.fa-exchange.bg-amber
  .timeline-item
    span.time
      i.fa.fa-clock-o = audit.created_at.strftime '%k:%M'
    h3.timeline-header Has been borrowed
    .timeline-body
      p
        - @item.item_histories.each do |history|
          - if history.rent_item && history.rent_item_id == audit.audited_changes['rent_item_id'].last
            = 'Been to: '
            - if history.rent_item.tenant.class == Contact
              b = history.rent_item.tenant.name
              = ','
              br
              - if history.rent_item.tenant.email.nil?
                = 'email: '
                b = history.rent_item.tenant.email
            - else
              b = history.rent_item.tenant.user_profile.first_name
              = ','
              br
              = 'email: '
              b = history.rent_item.tenant.email
              br
            = ' from '
            b = history.borrowed_at
            = ' to '
            b = history.returned_at
            = '.'

app/views/items/_shared_item_table.html.slim
- if borrowed_item.item
  tr
    td= link_to borrowed_item.title, rent_item_path(borrowed_item.id)
    td.hidden-xs.hidden-sm= borrowed_item.item.description
    td.hidden-xs.hidden-sm= borrowed_item.category&.name
    td.hidden-xs.hidden-sm= borrowed_item.item.display_created_at
    td
    td
    td.hidden-xs.hidden-sm= link_to edit_rent_item_path(borrowed_item) do
      i.material-icons edit
    td

app/views/items/_slider.html.slim
#myCarousel.carousel.slide data-ride="carousel"
  /! Indicators
  ol.carousel-indicators
    = indicators(item.attachments).html_safe
  /! Wrapper for slides
  .carousel-inner
    = slides(item.attachments).html_safe
  /! Left and right controls
  a.left.carousel-control data-slide="prev" href="#myCarousel"
    span.glyphicon.glyphicon-chevron-left
    span.sr-only Previous
  a.right.carousel-control data-slide="next" href="#myCarousel"
    span.glyphicon.glyphicon-chevron-right
    span.sr-only Next

app/views/items/_status_free_changed.html.slim
li
  i.fa.fa-gift.bg-cyan
  .timeline-item
    span.time
      i.fa.fa-clock-o = audit.created_at.strftime '%k:%M'
    - if audit.audited_changes['free'].last
      h3.timeline-header Became free
    - else
      h3.timeline-header Became not free

app/views/items/_timeline.html.slim
#timeline.row.clearfix
  .col-xs-12.col-sm-12.col-md-12.col-lg-12
    .card.history-item
      .header
        h2
          | History
      .body
        .row.clearfix
          ul.timeline
            - @item.audits.reverse_each do |audit|
              - unless audit.audited_changes['niche_id'] && audit.audited_changes['niche_id'].last.nil?
                - unless audit.audited_changes['rent_item_id'] && @item.item_histories.where(rent_item_id: audit.audited_changes['rent_item_id'].last).first.rent_item.nil?
                  li.time-label
                    span.bg-red = audit.created_at.strftime '%-d %b. %Y'
                  - if audit.audited_changes['title']
                    = render partial: 'title_changed', locals: { audit: audit }
                  - if audit.audited_changes['niche_id']
                    = render partial: 'niche_changed', locals: { audit: audit }
                  - if audit.audited_changes['category_id']
                    = render partial: 'category_changed', locals: { audit: audit }
                  - if audit.audited_changes['description']
                    = render partial: 'description_changed', locals: { audit: audit }
                  - if audit.audited_changes['rent_item_id']
                    = render partial: 'rent_item_changed', locals: { audit: audit }
                  - if audit.audited_changes['free']
                    = render partial: 'status_free_changed', locals: { audit: audit }
                  - if audit.audited_changes['attachments']
                    = render partial: 'photo_changed', locals: { audit: audit }
            li
              i.fa.fa-clock-o.bg-grey

app/views/items/_title_changed.html.slim
li
  i.fa.fa-edit.bg-purple
  .timeline-item
    span.time
      i.fa.fa-clock-o = audit.created_at.strftime '%k:%M'
    h3.timeline-header Title changed
    .timeline-body
      p
        b = audit.audited_changes['title'].first
        = ' to '
        b = audit.audited_changes['title'].last
        = '.'

app/views/items/index.html.slim
.row.clearfix
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    .card
      .header.table-header
        h2
          span ITEMS
          .tooltip
            = link_to new_item_path, class: 'btn-plus' do
              i.material-icons.col-green control_point
            .tooltiptext Create new item
      .body.table-responsive
        table.table.table-striped
          thead
            tr
              th = sort_link 'title'
              th colspan="1"
              th.hidden-xs.hidden-sm = 'Niche'
              th.hidden-xs.hidden-sm = 'Category'
              th.hidden-xs.hidden-sm = sort_link 'created_at', 'Created On'
          tbody
            = render partial: 'item_table', collection: @items, as: :item
        = will_paginate(@items, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'pagination-lg', previous_label: '<-', next_label: '->')
br/
br/
- if @lend_items.present?
  .row.clearfix
    .col-lg-12.col-md-12.col-sm-12.col-xs-12
      .card
        .header
          h2
            | LENT ITEMS
        .body.table-responsive
          table.table.table-striped
            thead
              tr
                th = 'Title'
                th colspan="3"
            tbody
              = render partial: 'lend_item_table', collection: @lend_items, as: :lend_item
br/
br/
- if @borrowed_items.present?
  .row.clearfix
    .col-lg-12.col-md-12.col-sm-12.col-xs-12
      .card
        .header
          h2
            | BORROWED ITEMS
        .body.table-responsive
          table.table.table-striped
            thead
              tr
                th = 'Title'
                th colspan="3"
            tbody
              = render partial: 'shared_item_table', collection: @borrowed_items, as: :borrowed_item
= render partial: 'templates/modal'

app/views/items/new.html.slim
.card
  .header
    h2
      | New Item
  .body
    = render 'form', item: @item

app/views/items/show.html.slim
link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" /

.row.clearfix
  .col-xs-12.col-sm-12.col-md-12.col-lg-12
    .card
      .header
        h2
          = @item.title
          - if @item.audits.count > 0
            .tooltip
              = link_to '#', id: 'history' do
                i.material-icons info
              .tooltiptext Item history
      .body
        .row.clearfix
          .col-xs-12.col-sm-6.col-md-6.col-lg-6
            - if @item.attachments.any?
              = render partial: 'slider', locals: { item: @item }
            - else
              = image_tag('page_size_image.png', class: 'default-image')
          .col-xs-12.col-sm-6.col-md-6.col-lg-6
            .text-left
              h2 Description
            p
              = @item.description
            h2 Category
            p
              = @item.category&.name
            h2 Niche
            p
              = @item.niche&.name
            p
              strong
              - if @item.free
                strong THIS ITEM IS FREE
            .buttons
              = link_to 'Edit', edit_item_path(@item), class: 'btn bg-blue-grey btn-lg'
              = link_to 'Back', items_path, class: 'btn bg-blue-grey btn-lg'
= render 'timeline'